### ISSUE TITLE
Issue Starting

### ISSUE THREAD

**Issue by seanodea** [vshn/puppet-in-docker#29]
Getting this error on puppetdb, haproxy, and maybe other systems.

/usr/lib/ruby/2.5.0/net/protocol.rb:44:in `connect_nonblock': SSL_connect returned=1 errno=0 state=error: certificate verify failed (unspecified certificate verification error) (OpenSSL::SSL::SSLError)

ERROR "global\n  log stdout local0\n  log stdout local1 notice\n  maxconn 2048\n  tune.ssl.default-dh-param 2048\n\ndefaults\n  log  global\n  mode  http\n  stats  enable\n  timeout  connect 5s\n  timeout  client 50s\n  timeout  tunnel 1h\n  timeout  http-request 10s\n  timeout  server 61m\n\nlisten stats\n  bind *:9000\n  mode http\n  stats enable\n  stats hide-version\n  stats refresh 30s\n  stats show-node\n  stats auth admin:password\n  stats uri /\n\nfrontend puppet-frontend\n  bind *:8140 ssl crt /usr/local/etc/haproxy/ssl/haproxy.pem ca-file /usr/local/etc/haproxy/ssl/certs/ca.pem verify optional crl-file /usr/local/etc/haproxy/ssl/crl.pem\n  mode http\n  http-request set-header X-Client-Verify-Real  %!\(BADINDEX)n  http-request set-header X-Client-Verify NONE if !{ hdr_val(X-Client-Verify-Real) eq 0 }\n  http-request set-header X-Client-Verify SUCCESS if { hdr_val(X-Client-Verify-Real) eq 0 }\n  http-request set-header X-Client-DN CN=%!{(MISSING)+Q}[ssl_c_s_dn(cn)]\n  http-request set-header X-SSL-Subject CN=%!{(MISSING)+Q}[ssl_c_s_dn(cn)]\n  http-request set-header X-Client-Cert \"-----BEGIN CERTIFICATE-----%0A%%!A(MISSING)-----END CERTIFICATE----- #\" if { ssl_c_used }\n  # /puppet-ca/v1/:indirection/:key?environment=:environment\n  acl ca_current path -m beg /puppet-ca\n  acl catalog path -m beg /puppet/v3/catalog\n  # /:environment/certificate/:nodename\n  default_backend puppet-default-backend\n  use_backend puppet-ca-backend if ca_current\n  use_backend puppet-catalog-backend if catalog\n\nbackend puppet-default-backend\n  balance roundrobin\n  mode http\n  option tcp-check\n  stick on src\n  stick-table type ip size 1m expire 1m\n  server puppetserver puppetserver.local:8140 check port 8140 inter 5s ssl verify required ca-file /usr/local/etc/haproxy/ssl/certs/ca.pem crl-file /usr/local/etc/haproxy/ssl/crl.pem\n\nbackend puppet-catalog-backend\n  balance roundrobin\n  mode http\n  option tcp-check\n  stick on src\n  stick-table type ip size 1m expire 1m\n  server puppetserver puppetserver.local:8140 check port 8140 inter 5s ssl verify required ca-file /usr/local/etc/haproxy/ssl/certs/ca.pem crl-file /usr/local/etc/haproxy/ssl/crl.pem\n\nbackend puppet-ca-backend\n  mode http\n  option tcp-check\n  server puppetca puppetca.local:8140 check port 8140 inter 5s ssl verify required ca-file /usr/local/etc/haproxy/ssl/certs/ca.pem crl-file /usr/local/etc/haproxy/ssl/crl.pem\n[ALERT] 127/073034 (39) : parsing [/usr/local/etc/haproxy/.haproxy.cfg767642560:28] : 'bind *:8140' : unable to load SSL certificate file '/usr/local/etc/haproxy/ssl/haproxy.pem' file does not exist.\n[ALERT] 127/073034 (39) : Error(s) found in configuration file : /usr/local/etc/haproxy/.haproxy.cfg767642560\n[ALERT] 127/073034 (39) : Fatal errors found in configuration.\n"

**Comment by seanodea** [comment]
I am simply cloning your repo in the latest ubuntu and running docker-compose up.

**Comment by seanodea** [comment]
When I do docker-compose up puppetca puppetdb only it shows this at the end:

```
puppetca_1      |    (location: /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet.rb:133:in `Puppet')
puppetca_1      | 2020-05-07 07:45:26,251 INFO  [puppetserver] Puppet Puppet settings initialized; run mode: master
puppetca_1      | 2020-05-07 07:45:27,004 INFO  [p.s.j.i.jruby-agents] Finished creating JRubyInstance 2 of 2
puppetdb_1      | ---> Requesting certificate for puppetdb from puppetca.local
puppetca_1      | 172.18.0.4 - - - 07/May/2020:07:45:30 +0000 "GET /puppet-ca/v1/certificate/ca HTTP/1.1" 200 1923 172.18.0.4 172.18.0.4 8140 74
puppetdb_1      | ----> Creating SSL dirs
puppetdb_1      | ----> Requesting CA from 'puppetca.local'
puppetdb_1      | ----> Requesting CRL from 'puppetca.local'
puppetdb_1      | /usr/lib/ruby/2.5.0/net/protocol.rb:44:in `connect_nonblock': SSL_connect returned=1 errno=0 state=error: certificate verify failed (unspecified certificate verification error) (OpenSSL::SSL::SSLError)
puppetdb_1      |       from /usr/lib/ruby/2.5.0/net/protocol.rb:44:in `ssl_socket_connect'
puppetdb_1      |       from /usr/lib/ruby/2.5.0/net/http.rb:985:in `connect'
puppetdb_1      |       from /usr/lib/ruby/2.5.0/net/http.rb:920:in `do_start'
puppetdb_1      |       from /usr/lib/ruby/2.5.0/net/http.rb:909:in `start'
puppetdb_1      |       from /usr/lib/ruby/2.5.0/net/http.rb:1458:in `request'
puppetdb_1      |       from /usr/local/bin/request-cert.rb:142:in `fetch_crl'
puppetdb_1      |       from /usr/local/bin/request-cert.rb:244:in `<main>'
puppetdb_1      | ---> Certificate retrieval failed. Exiting
puppetdb_1      | run-parts: /docker-entrypoint.d/11-tls-setup.sh exited with return code 1
puppetdb_1      | run-parts: executing /docker-entrypoint.d/20-whitelist.sh
puppetdb_1      | ---> Configuring PuppetDB whitelist
puppet-in-docker_puppetdb_1 exited with code 1
```
